apps/Documentos/urls.py
from django.urls import path, include
from . import views
from  django.conf import settings
from django.contrib.staticfiles.urls import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('index/documentos', views.documentos, name='index_documentos'),
    path('index/informes', views.informes, name='index_informes'),
    path('documentos', views.crear_documento, name='subir_documentos'),
    path('informes', views.crear_informe, name='subir_informe'),
    path('eliminar/informe/<int:id>', views.eliminar_archivo, name='eliminar_archivo'),
    path('usuarios/documentos', views.listar_documentos, name='listar_documentos'),
    path('usuarios/informes', views.listar_informes, name='listar_informes'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Usuarios/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static

app_name = 'usersAuth'

urlpatterns = [
    path('principal/', views.principal, name='principal'),
    path('register/', views.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('accounts/login/ingreso/', views.ingreso, name='ingreso'),
    path('usuarios/activos', views.usuarios_activos, name='usuarios_activos'),
    path('usuarios/inactivos', views.usuarios_inactivos, name='usuarios_inactivos'),
    path('rechazar/<int:id>', views.rechazar_preregistro, name='rechazar_registro'),
    path('usuarios/aceptacion/<int:id>', views.aceptar_preregistro, name='aceptar'),
    path('index/usuarios', views.index_usuario, name='index_usuarios'),
    path('index/nosotros', views.index_nosotros, name='index_nosotros'),
    path('', include('apps.Documentos.urls')),
    path('', include('apps.Perfiles.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

procesamientolenguajenatural/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.Usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

apps/Usuarios/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

class Tipo(models.Model):
    id = models.BigAutoField(primary_key=True)
    tipo = models.CharField(max_length=250, blank=False, null=False)

    class Meta:
        verbose_name = 'Tipo'
        verbose_name_plural = 'Tipos'
        ordering = ['tipo']

    def __str__(self):
        return self.tipo


class CustomUser(User):
    tipo_id = models.ForeignKey(Tipo, on_delete=models.CASCADE, verbose_name='Tipo de persona')

apps/Usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields =  ['first_name', 'last_name','username','email', 'password1', 'password2',]

    # Check unique email
    # Email exists && account active -> email_already_registered
    # Email exists && account not active -> delete previous account and register new one
    def clean_email(self):
        email_passed = self.cleaned_data.get("email")
        email_already_registered = User.objects.filter(email = email_passed).exists()
        user_is_active = User.objects.filter(email = email_passed, is_active = 1)
        if email_already_registered and user_is_active:
            #print('email_already_registered and user_is_active')
            raise forms.ValidationError("Email already registered.")
        elif email_already_registered:
            #print('email_already_registered')
            User.objects.filter(email = email_passed).delete()

        return email_passed

apps/Usuarios/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
UserModel = get_user_model()
from django.template.loader import get_template
from  django.core.mail import EmailMultiAlternatives
from django.conf import settings
from .forms import RegisterUserForm


def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('rxWod:index'))
    else:
        if request.method == 'POST':
            form = RegisterUserForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.is_active = False
                user.save()
                messages.add_message(request=request, level=messages.SUCCESS, message="Su registro se ha realizado con éxito")
                return render(request, 'pages/index.html')
            else:
                if form.errors:
                    for key, values in form.errors.as_data().items():
                        if key == 'email':
                            messages.info(request, 'Correo registrado')
                            break
                        else:
                            for error_value in values:
                                messages.info(request, '%s' % (error_value.message))
                return HttpResponseRedirect(reverse('usersAuth:register'))
        else:
            form = RegisterUserForm()
            context = {
                'form': form
            }
            return render(request, 'usersAuth/register.html', context)

def principal(request):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            return render(request, 'admin/principal.html')
        else:
            return render(request, 'usuario/index.html')
    else:
        return render(request, 'pages/index.html')

def index(request):
    return render(request, 'pages/index.html')

def index_nosotros(request):
    return render(request, 'pages/nosotros.html')


def ingreso(request):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            return render(request, 'admin/principal.html')
        else:
            return render(request, 'usuario/index.html')
    # Do something for authenticated users.
    else:
        return render(request, 'pages/index.html')

def index_usuario(request):
    if request.user.is_authenticated:
        if request.user.is_superuser == False:
            return render(request, 'usuario/index.html')
        else:
            return render(request, 'admin/principal.html')
    else:
        return render(request, 'pages/index.html')


def usuarios_activos(request):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            lista_usuarios = User.objects.all()
            return render(request, 'admin/usuarios_activos.html', {'lista_usuarios': lista_usuarios})
        else:
            return render(request, 'usuario/index.html')
    else:
        return render(request, 'pages/index.html')

def usuarios_inactivos(request):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            lista_usuarios = User.objects.all()
            return render(request, 'admin/usuarios_inactivos.html', {'lista_usuarios': lista_usuarios})
        else:
            return render(request, 'usuario/index.html')
    else:
        return render(request, 'pages/index.html')

def send_email(nombre, mail, estado_id):
        context = {'nombre': nombre, 'estado_id': estado_id}
        template = get_template('admin/correo.html')
        content = template.render(context)
        email = EmailMultiAlternatives(
            'PROCESAMIENTO DE LENGUAJE NATURAL',
            'Procesamiento de lenguaje natural',
            settings.EMAIL_HOST_USER,
            [mail]
        )
        email.attach_alternative(content, 'text/html')
        email.send()


def aceptar_preregistro(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            preregistro = User.objects.get(id=id)
            preregistro.is_active = True
            preregistro.save()
            mail = preregistro.email
            nombre = preregistro.first_name
            estado_id = preregistro.is_active
            send_email(nombre, mail, estado_id)
            messages.add_message(request=request, level=messages.SUCCESS, message="Se ha enviado el correo de notificación")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return render(request, 'pages/index.html')


def rechazar_preregistro(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            preregistro = User.objects.get(id=id)
            preregistro.is_active = False
            preregistro.save()
            mail = preregistro.email
            nombre = preregistro.first_name
            estado_id = preregistro.is_active
            send_email(nombre, mail, estado_id)
            messages.add_message(request=request, level=messages.SUCCESS, message="Se ha enviado el correo de notificación")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return render(request, 'pages/index.html')

apps/Usuarios/templates/pages/index.html
{% extends "pages/master_principal.html" %}
{% block title %} Procesamiento de Lenguaje Natural {% endblock %}
{% block subtitle %} Procesamiento de Lenguaje Natural {% endblock %}
{% block contenido %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    <h1 class="mx-auto my-0 text-uppercase justify-content-xl-center">Procesamiento de Lenguaje Natural</h1>
    <pre>
        <h3 class="mx-auto my-0 text-uppercase align-content-center">Universidad de Cundinamarca - Extensión Facatativá</h3>
        <h3 class="mx-auto my-0 text-uppercase">Ingeniería de Sistemas</h3>
    </pre>
{% endblock %}

apps/Usuarios/templates/pages/iniciar_sesion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>inicia sesion</title>
</head>
<body>
    <form action="" method="POST">

        <input type="submit" name="submit">
    </form>
</body>
</html>

apps/Usuarios/templates/pages/master_principal.html
{% load static %}
<!DOCTYPE html><html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/stylesR.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">{% block subtitle %}{% endblock %}</span>
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'assets/img/udec.jpg' %}" alt="..." /></span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" >{{ user.get_username }}</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'usersAuth:principal' %}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'usersAuth:index_informes' %}">Informes</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'usersAuth:index_documentos' %}">Documentación</a></li>
                            <li class="nav-item">
                                <a class="nav-link js-scroll-trigger" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                    Usuarios
                                </a>
                                <li class="nav-item">
                                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="{% url 'usersAuth:usuarios_activos' %}">Usuarios Habilitados</a>
                                            <a class="nav-link" href="{% url 'usersAuth:usuarios_inactivos' %}">Usuarios Inhabilitados</a>
                                        </nav>
                                    </div>
                                </li>
                            </li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'usersAuth:register' %}">Registrar</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'usersAuth:index_nosotros' %}">Nosotros</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'usersAuth:login' %}">Ingresar</a></li>
                        {% endif %}

                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'logout'%}?next={{request.path}}">Cerrar sesión</a></li>
                        {% endif %}


                </ul>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container-fluid p-0">
            <!-- About-->
            <section class="resume-section" id="about">
                <div class="resume-section-content">
                    {% block contenido %}{% endblock %}
                </div>
            </section>

        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scriptsR.js' %}"></script>
    </body>
</html>

apps/Usuarios/templates/pages/nosotros.html
{% extends "pages/master_principal.html" %}
{% block title %} Procesamiento de Lenguaje Natural - Nosotros {% endblock %}
{% block contenido %}
    <h1 class="mx-auto my-0 text-uppercase justify-content-xl-center">Procesamiento de Lenguaje Natural</h1>
    <pre>
        <h6 class="mx-auto my-0 text-uppercase">
            Tomando en conjunto el ámbito educativo y ocupacional,en un país como Colombia, en el cual
            el 22,1% de los asalariados desean cambiar de empleo, según un informe de observatorio laboral
            de la Universidad del Rosario, es válido afirmar que en su mayoría se debe a la inconformidad
            de los trabajadores de acuerdo a su trabajo, ya que no se desempeñan en un ámbito que se adecue
            a sus conocimientos; esto porque en gran parte su desarrollo educativo suele ser diferente a la
            oferta laboral.
            Es por esto que se desarrolló un aplicativo web, con el fin de mostrar al usuario perfiles
            ocupacionales semejantes a su búsqueda, que tenga un mayor porcentaje de coincidencia con los
            perfiles ocupacionales de distintas universidades. Incorporando de igual forma un control sobre
            los perfiles inscritos, a lo cual el usuario tiene acceso en dicha plataforma. </h6>
    </pre>
{% endblock %}