apps/Perfiles/urls.py
from django.urls import path, include
from . import views
from  django.conf import settings
from django.contrib.staticfiles.urls import static
from django.views.static import serve
from django.conf.urls import url


urlpatterns = [
    path('index/perfiles', views.perfiles, name='index_perfiles'),
    path('index/perfiles/historico', views.reportehistorico, name='index_perfiles_historico'),
    path('index/pdf', views.reporte_personas, name='index_pdf'),
    path('crear/perfil', views.crear_perfil, name='crear_perfil'),
    path('perfil/inhabilitar/<int:id>', views.inhabilitar_perfil, name='inhabilitar_perfil'),
    path('index/perfiles/usuarios', views.perfiles_usuario, name='index_perfiles_usuarios'),
    path('index/perfiles/<int:id>', views.editar_perfil, name='index_editar_perfil'),
    path('index/historico/<int:id>', views.perfiles_resultado, name='index_historico_resultado'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Usuarios/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static

app_name = 'usersAuth'

urlpatterns = [
    path('principal/', views.principal, name='principal'),
    path('register/', views.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('accounts/login/ingreso/', views.ingreso, name='ingreso'),
    path('usuarios/activos', views.usuarios_activos, name='usuarios_activos'),
    path('usuarios/inactivos', views.usuarios_inactivos, name='usuarios_inactivos'),
    path('rechazar/<int:id>', views.rechazar_preregistro, name='rechazar_registro'),
    path('usuarios/aceptacion/<int:id>', views.aceptar_preregistro, name='aceptar'),
    path('index/usuarios', views.index_usuario, name='index_usuarios'),
    path('index/nosotros', views.index_nosotros, name='index_nosotros'),
    path('', include('apps.Documentos.urls')),
    path('', include('apps.Perfiles.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

procesamientolenguajenatural/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.Usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

apps/Perfiles/models.py
from django.db import models

class estado_perfil(models.Model):
    id = models.BigAutoField(primary_key=True)
    estado = models.CharField(max_length=250, blank=False, null=False)

    class Meta:
        verbose_name = 'Estado'
        verbose_name_plural = 'Estado'
        ordering = ['estado']

    def __str__(self):
        return self.estado

class perfiles_ocupacionales(models.Model):
    id = models.AutoField(primary_key=True)
    universidad = models.CharField(max_length=100, verbose_name='Universidad')
    programa = models.CharField(max_length=100, null=False, verbose_name='Programa')
    perfil = models.TextField(verbose_name='Perfil Ocupacional')
    estado_id = models.ForeignKey(estado_perfil, default=1, on_delete=models.CASCADE, verbose_name='Estado')
    fecha_creacion = models.DateField('Fecha de creacion', auto_now=True, auto_now_add=False)


class historico(models.Model):
    id = models.AutoField(primary_key=True)
    busqueda = models.TextField(verbose_name='Busqueda')
    perfiles = models.CharField(max_length=200, null=False, verbose_name='Perfiles')
    fecha_creacion = models.DateField('Fecha de creacion', auto_now=True, auto_now_add=False)

apps/Perfiles/forms.py
from django import forms
from .models import perfiles_ocupacionales, historico

class PerfilesForm(forms.ModelForm):
    class Meta:
        model = perfiles_ocupacionales
        fields = ['universidad','programa','perfil']

class FiltroBusqueda():
    class Meta:
        fields = ['filtro']

class HistoricoForm(forms.ModelForm):
    class Meta:
        model = historico
        fields = ['busqueda','perfiles']

apps/Perfiles/views.py
from string import punctuation
from django.http import HttpResponseRedirect, HttpResponse
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from .forms import PerfilesForm
from .models import perfiles_ocupacionales, historico
from django.shortcuts import render, redirect
from django.contrib import messages

language_stopwords = stopwords.words('spanish')

non_words = list(punctuation)


from .reportes import ReportePersona

def reporte_personas(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="personas.pdf"'
    r = ReportePersona()
    response.write(r.run())
    return response

def reportehistorico(request):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            lista_perfiles = historico.objects.all()
            cont = 0
            if not lista_perfiles:
                cont = 1
            return render(request, 'admin_perfiles/historico.html', {'lista_perfiles': lista_perfiles, 'cont': cont})
        else:
            return render(request, 'usuario/index.html')
    else:
        return render(request, 'pages/index.html')

def perfiles_resultado(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            characters = "[] "
            resultado = historico.objects.get(id=id)
            arrayperfiles = resultado.perfiles
            cont = 1
            array2 = []
            lista_perfiles = perfiles_ocupacionales.objects.all()
            for x in range(len(characters)):
                arrayperfiles = arrayperfiles.replace(characters[x], "")
            if arrayperfiles != "":
                cont=0
                conta=0
                subcadena = ""
                prueba = ""
                if ',' in arrayperfiles:
                    for cadena in arrayperfiles:
                        conta +=1
                        if cadena != ",":
                            subcadena = subcadena + cadena
                            if conta == len(arrayperfiles):
                                array2 = array2 + [subcadena]
                        else:
                            array2 = array2 + [subcadena]
                            subcadena = ""
                    if conta == len(arrayperfiles):
                        arrayperfiles = array2
                else:
                    arrayperfiles = [arrayperfiles]

                arrayperfiles = list(arrayperfiles)
                idfiltro = str(arrayperfiles[0])
                idfiltro = int(idfiltro)
                arrayperfiles.pop(0)
                lista_perfiles = perfiles_ocupacionales.objects.filter(id=int(idfiltro))
                for idperfil in arrayperfiles:
                    idperfil2 = str(idperfil)
                    idbusqueda = int(idperfil2)
                    lista_perfiles = lista_perfiles | perfiles_ocupacionales.objects.filter(id=idbusqueda)

            return render(request, 'admin_perfiles/historico_busqueda.html', {'lista_perfiles': lista_perfiles, 'cont': cont})
        else:
            return render(request, 'usuario/index.html')
    else:
        return render(request, 'pages/index.html')

def perfiles(request):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            lista_perfiles = perfiles_ocupacionales.objects.filter(estado_id=1)
            cont = 0
            if not lista_perfiles:
                cont = 1
            return render(request, 'admin_perfiles/index.html', {'lista_perfiles': lista_perfiles, 'cont': cont})
        else:
            return render(request, 'usuario/index.html')
    else:
        return render(request, 'pages/index.html')

def crear_perfil(request):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            formulario_perfil = PerfilesForm(request.POST or None, request.FILES or None)
            if formulario_perfil.is_valid():
                formulario_perfil.save()
                messages.add_message(request=request, level=messages.SUCCESS, message="Perfil ocupacional registrado con éxito")
                return redirect('usersAuth:index_perfiles')
            return render(request, 'admin_perfiles/create.html', {'formulario_perfil': formulario_perfil})
        else:
            return render(request, 'usuario/index.html')
    else:
        return render(request, 'pages/index.html')

def inhabilitar_perfil(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser == True:
            perfil = perfiles_ocupacionales.objects.get(id=id)
            perfil.estado_id_id = 2
            perfil.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            return render(request, 'usuario/index.html')
    else:
        return render(request, 'pages/index.html')

def eliminacion_stopwords(text):
    texto_limpio = ''
    for word in text.split():
        if word in language_stopwords or word in non_words:
            continue
        else:
            texto_limpio += word + ' '
    return texto_limpio

def eliminar_puntuacion(string_inicial):
    for word in non_words:
        string_inicial = string_inicial.replace(word, '')
    return string_inicial

def procesar_texto(textnlp):
    text_content = textnlp
    text_content = text_content.lower()
    text_content = eliminar_puntuacion(text_content)
    text_content = eliminacion_stopwords(text_content)
    return text_content


def perfiles_usuario(request):
    if request.user.is_authenticated:
        if request.user.is_superuser == False:
            lista_perfiles = perfiles_ocupacionales.objects.filter(estado_id=1)
            cont = 0
            if not lista_perfiles:
                cont = 1
            querysetfiltro = request.GET.get("filtro")
            querysetbusqueda = request.GET.get("busqueda")
            text = str(querysetbusqueda)
            nlp_text = procesar_texto(text)
            mayor = 0
            menor = 0
            porcentajemayor = ""
            porcentajemenor = ""
            pruebas =  ["10","2","5"]
            if querysetfiltro == '1':
                vector_perfiles = []
                for textprocesamiento in lista_perfiles:
                    institucion = str(textprocesamiento.universidad)
                    nlp_registro = procesar_texto(institucion)
                    vectorizer = TfidfVectorizer()
                    X = vectorizer.fit_transform([nlp_text, nlp_registro])
                    similarity_matrix = cosine_similarity(X, X)

                    #print('institución', similarity_matrix)
                    if(similarity_matrix[0][1] >= 0.5):
                        if(similarity_matrix[0][1] > mayor):
                            mayor = similarity_matrix[0][1]
                            #porcentaje = similarity_matrix[0][1]
                            #porcentajes = "{:%}".format(porcentaje)
                        if (similarity_matrix[0][1] < menor):
                            menor = similarity_matrix[0][1]
                            # porcentaje = similarity_matrix[0][1]
                            # porcentajes = "{:%}".format(porcentaje)

                        vector_perfiles = vector_perfiles + [textprocesamiento.id]
                porcentajemenor = "{:%}".format(menor)
                porcentajemayor = "{:%}".format(mayor)
                if vector_perfiles:
                    idfiltro = vector_perfiles[0]
                    aux = []
                    contaux = -1
                    vector_perfiles.pop(0)
                    variable = '0'
                    perfil_array = perfiles_ocupacionales.objects.filter(id=idfiltro)
                    for idperfil in vector_perfiles:
                        contaux=+1

                        perfil_array = perfil_array | perfiles_ocupacionales.objects.filter(id=idperfil)

                    return render(request, 'usuariosperfil/filtro.html', {'perfil_array': perfil_array, 'porcentajemayor': porcentajemayor, 'porcentajemenor': porcentajemenor})
                else:
                    cont = 2
                    return render(request, 'usuariosperfil/index.html',{'lista_perfiles': lista_perfiles, 'cont': cont})
            elif querysetfiltro == '2':
                vector_perfiles = []
                vector_prueba = []
                for textprocesamiento in lista_perfiles:
                    programa = str(textprocesamiento.programa)
                    nlp_registro = procesar_texto(programa)
                    vectorizer = TfidfVectorizer()
                    X = vectorizer.fit_transform([nlp_text, nlp_registro])
                    similarity_matrix = cosine_similarity(X, X)
                    print('programa',similarity_matrix)
                    if(similarity_matrix[0][1] >= 0.2):
                        vector_perfiles = vector_perfiles + [textprocesamiento.id]
                        if (similarity_matrix[0][1] > mayor):
                            mayor = similarity_matrix[0][1]
                            # porcentaje = similarity_matrix[0][1]
                            # porcentajes = "{:%}".format(porcentaje)
                        if (similarity_matrix[0][1] < menor):
                            menor = similarity_matrix[0][1]
                            # porcentaje = similarity_matrix[0][1]
                            # porcentajes = "{:%}".format(porcentaje)
                porcentajemenor = "{:%}".format(menor)
                porcentajemayor = "{:%}".format(mayor)
                if vector_perfiles:
                    idfiltro = vector_perfiles[0]
                    vector_perfiles.pop(0)
                    perfil_array = perfiles_ocupacionales.objects.filter(id=idfiltro)
                    lista_perfiles = perfiles_ocupacionales.objects.all()

apps/Perfiles/templates/admin_perfiles/create.html
{% extends "admin/master_admin.html" %}
{% block title %} CREAR PERFILES OCUPACIONES {% endblock %}

{% block contenido %}

     <div class="card">
        <div class="card-header">

        </div>
        <div class="card-body">
            <h4 class="card-title">Perfiles Ocupacionales</h4>
            {% include 'admin_perfiles/forms.html' %}

        </div>
        <div class="card-footer text-muted">

        </div>
    </div>

{% endblock %}

apps/Perfiles/templates/admin_perfiles/forms.html
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
        {{ formulario_perfil.as_p }}
    <input name="" id="" class="btn btn-success" type="submit" value="Registrar perfil">
    <a name="" id="" class="btn btn-primary" href="{% url 'usersAuth:index_perfiles' %}" role="button">Regresar</a>
</form>

apps/Perfiles/templates/admin_perfiles/historico.html
{% extends "admin/master_admin.html" %}
{% block title %} PERFILES OCUPACIONES {% endblock %}
{% block contenido %}

     <div class="card">

        <div class="card-body">
            {% if cont == 1 %}
                <h1 class="card-title">POR EL MOMENTO NO SE HAN REALIZADO BÚSQUEDA</h1>
            {% endif %}
            {% if cont == 0%}
                <h4 class="card-title">Histórico</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>BÚsqueda</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for perfiles in lista_perfiles  %}
                        <tr>
                               <td>{{ perfiles.busqueda }}</td>
                                <td>
                                    <a name="" id="" class="btn btn-warning" href="{% url 'usersAuth:index_historico_resultado' perfiles.id %}"  role="button">VER RESULTADOS</a>
                                    <hr>
                                </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

apps/Perfiles/templates/admin_perfiles/historico_busqueda.html
{% extends "admin/master_admin.html" %}
{% block title %} PERFILES OCUPACIONES {% endblock %}
{% block contenido %}

     <div class="card">
        <div class="card-footer text-muted" id="button">
            <a name="" id="" onclick="miFunc()" class="btn btn-primary" style="float: right;" role="button">Descargar PDF</a>
        </div>
        <div class="card-body" id="perfiles_table">

            {% if cont == 1 %}
                <h2 class="card-title">NO SE ENCONTRARON PERFILES SIMILARES A LA BÚSQUEDA</h2>
            {% endif %}
            {% if cont == 0%}
                <h4 class="card-title">Perfiles Ocupacionales</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Universidad</th>
                            <th>Programa</th>
                            <th>Perfil</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for perfiles in lista_perfiles  %}
                        <tr>
                               <td>{{ perfiles.universidad }}</td>
                                <td>{{ perfiles.programa }}</td>
                                <td>{{ perfiles.perfil }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
        <div class="card-footer text-muted" id="button">
            <a name="" id="" class="btn btn-primary" href="{% url 'usersAuth:index_perfiles_historico' %}" role="button">Regresar</a>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="html2pdf.bundle.min.js"></script>
    <script>
      function miFunc() {
          var element = document.getElementById('perfiles_table');
          var opt = {
              margin:       0.4,
              filename:     'resultados.pdf',
              image:        { type: 'jpeg', quality: 0.90 },
              html2canvas:  { scale: 2 },
              jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
            };

            // New Promise-based usage:
            html2pdf().set(opt).from(element).save();


      }
    </script>
{% endblock %}

apps/Perfiles/templates/admin_perfiles/index.html
{% extends "admin/master_admin.html" %}
{% block title %} PERFILES OCUPACIONES {% endblock %}
{% block contenido %}

     <div class="card">
     {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
            </li>
            {% endfor %}
        </ul>
    {% endif %}
        <div class="card-header">
            <p class="lead">
                <a class="btn btn-success btn-lg" href="{% url 'usersAuth:crear_perfil' %}" role="button">Registrar Perfil</a>
            </p>
        </div>
        <div class="card-body">
            {% if cont == 1 %}
                <h1 class="card-title">POR EL MOMENTO NO HAY REGISTRADO NINGÚN PERFIL</h1>
            {% endif %}
            {% if cont == 0%}
                <h4 class="card-title">Perfiles Ocupacionales</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Universidad</th>
                            <th>Programa</th>
                            <th>Perfil</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for perfiles in lista_perfiles  %}
                        <tr>
                               <td>{{ perfiles.universidad }}</td>
                                <td>{{ perfiles.programa }}</td>
                                <td>{{ perfiles.perfil }}</td>
                                <td>
                                    <a name="" id="" class="btn btn-warning" href="{% url 'usersAuth:index_editar_perfil' perfiles.id %}"  role="button">Editar</a>
                                    <hr>
                                    <a name="" id="" class="btn btn-warning" href="{% url 'usersAuth:inhabilitar_perfil' perfiles.id %}" onclick="return confirm('¿Está seguro de inhabilitar éste perfil?')"; role="button">Inhabilitar</a>
                                </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}